tsoding/ray-tracer

.gitignore

This folder is gennerated by the build on MacOS.

Added `ray-tracer.dSYM` to .gitignore.

---

Makefile
main.cpp

(#1) Perspective projection

---

main.cpp

(#3) Make scene support several spheres

---

main.cpp

(#8) Dimmer color on loger rays

---

.gitignore
.travis.yml
CPPLINT.cfg
Makefile
README.md
main.cpp
vec.h

(#10) Travis CI

---

.travis.yml

(#44) Use latest gcc from ubuntu-toolchain-r/test

---

.travis.yml

(#47) Enable clang build

---

CMakeLists.txt
src/main.cpp

Trace it randomly trace it nice

---

.gitignore
CMakeLists.txt
CPPLINT.cfg
cmake/CppLint.cmake
misc/cpplint.py
src/main.cpp

(#51) Integrate cpplint with cmake build

---

.travis.yml
src/color.hpp
src/main.cpp

(#52) C++17 on CI

---

src/main.cpp

(#55) Percentage progress for file render mode

---

CMakeLists.txt
src/color.cpp
src/color.hpp
src/main.cpp
src/scene.cpp

Not used to making PR's, so kindly correct me when I'm doing something wrong.

(#60) Downgrade to C++14

---

CMakeLists.txt
src/main.cpp
src/sprite_display.cpp
src/sprite_display.hpp

(#72) SpriteDisplay

---

CMakeLists.txt
src/display.cpp
src/display.hpp
src/main.cpp
src/parallel_rendering_scene.hpp
src/texture_display.cpp
src/texture_display.hpp

(#5) Introduce ParallelRenderingScene

---

src/arguments.cpp
src/arguments.hpp
src/main.cpp

(#81) Enable width and height for CLI arguments

---

src/scene.cpp

(#86) Check for division by zero

---

src/scene.cpp

(#87) Implement wall shadows for tracing

---

.travis.yml
CMakeLists.txt

(#92) Run linter as separate step on CI

---

src/scene.cpp

(#88) Add spheres support

---

CMakeLists.txt
src/color.cpp
src/color.hpp
src/display.cpp
src/display.hpp
src/ray.cpp
src/ray.hpp
src/scene.cpp
src/scene.hpp
src/sprite_display.hpp
src/texture_display.cpp
src/texture_display.hpp
src/wall.hpp

(#96) Fix sphere/wall order

---

src/ray.cpp
src/ray.hpp
src/scene.cpp

 (#97) Implement circle reflection
